KS-21-1
smokewolfy/KotlinSprint pull request #102
Opened 2024-06-14 10:06 UTC by smokewolfy

2024-06-15 11:43 UTC, ievetrovdev requested changes

2024-06-15 11:43 UTC, ievetrovdev commented on src/main/kotlin/lesson21/lesson21_task1.kt
> +    var vowelCount = 0
Попробуй более короткий вариант с помощью `return this.count { it in vowels }`

2024-06-15 11:43 UTC, ievetrovdev commented on src/main/kotlin/lesson21/lesson21_task1.kt
> +const val vowels = "aeiouyAEIOUY"
Неверный синтаксис константы

2024-06-15 12:15 UTC, smokewolfy commented on src/main/kotlin/lesson21/lesson21_task1.kt
> +    var vowelCount = 0
Сколько всего ещё нужно узнать)

2024-06-16 07:28 UTC, ievetrovdev approved these changes

2024-06-16 09:37 UTC, merged