Ks 21 2
smokewolfy/KotlinSprint pull request #104
Opened 2024-06-15 07:30 UTC by smokewolfy

2024-06-16 07:08 UTC, ievetrovdev requested changes

2024-06-16 07:08 UTC, ievetrovdev commented on src/main/kotlin/lesson21/lesson21_task2.kt
> +    this.forEach {
Предлагаю уже максимально использовать инструменты языка и для поиска суммы использовать соответствующие экстеншены: для фильтрации и нахождения суммы.

2024-06-16 10:45 UTC, smokewolfy commented on src/main/kotlin/lesson21/lesson21_task2.kt
> +    this.forEach {
вроде должно быть так

2024-06-17 09:48 UTC, ievetrovdev approved these changes

2024-06-17 15:19 UTC, merged