KS-5-2
smokewolfy/KotlinSprint pull request #18
Opened 2024-02-03 03:53 UTC by smokewolfy

2024-02-03 06:29 UTC, ievetrovdev requested changes

2024-02-03 06:29 UTC, ievetrovdev commented on src/main/kotlin/lesson5/lesson5_task2.kt
> +    val resultText = if (userAge >= AGE_OF_MAJORITY) "Показать экран со скрытым контентом"
Здесь использовать when более уместно

2024-02-03 06:29 UTC, ievetrovdev commented on src/main/kotlin/lesson5/lesson5_task2.kt
> +    else if (userAge == 16 || userAge == 17) "Показать экран с ограниченным контентом"
Если уж 18 вывел в конституцию, почему про 16 и 17 забыл?)

2024-02-03 06:42 UTC, smokewolfy commented on src/main/kotlin/lesson5/lesson5_task2.kt
> +    else if (userAge == 16 || userAge == 17) "Показать экран с ограниченным контентом"
В задании было изменить способ проверки возраста по образцу из видео, а не привести его в божеский вид) изменю.

2024-02-04 07:42 UTC, ievetrovdev approved these changes
Привидение в божеский вид почти всегда нужно, особенно когда это не требует больших усилий)

2024-02-16 10:35 UTC, merged