KS-9-5
smokewolfy/KotlinSprint pull request #38
Opened 2024-02-16 17:26 UTC by smokewolfy

2024-02-17 16:28 UTC, ievetrovdev requested changes

2024-02-17 16:28 UTC, ievetrovdev commented on src/main/kotlin/lesson9/lesson9_task5.kt
> +        .capitalize()
'capitalize(): String' is deprecated. Use replaceFirstChar instead.

Метод capitalize является устаревшим и не поддерживаемым (deprecated). Нужна альтернатива. Попробуй изучить подсказку в IDEA и доработать на актуальный метод

2024-02-17 16:29 UTC, smokewolfy commented on src/main/kotlin/lesson9/lesson9_task5.kt
> +        .capitalize()
Я видел , но замена мне показалась слишком громоздкой.

2024-02-21 08:59 UTC, ievetrovdev approved these changes

2024-02-24 17:02 UTC, merged