Ks 1 5
smokewolfy/KotlinSprint pull request #5
Opened 2024-01-28 08:54 UTC by smokewolfy

2024-01-29 00:25 UTC, ievetrovdev requested changes

2024-01-29 00:25 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +    val crystalOre = 7
этот файл не относится к заданию. давай его удалим

чтобы такого не происходило в будущем тебе необходимо после получения аппрува мержить ветку в мастер. а также новые ветки всегда делать только от мастера и перед этим сделав в него `pull`

2024-01-29 00:25 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val secondsInSpace = 6480
по заданию все ок)

2024-01-30 16:50 UTC, smokewolfy commented on src/main/kotlin/lesson2/lesson2_task4.kt
> +    val crystalOre = 7
> этот файл не относится к заданию. давай его удалим
> 
> чтобы такого не происходило в будущем тебе необходимо после получения аппрува мержить ветку в мастер. а также новые ветки всегда делать только от мастера и перед этим сделав в него `pull`
Я уже по ходу дела разобрался почему так произошло.

2024-02-01 00:14 UTC, ievetrovdev approved these changes

2024-02-24 17:11 UTC, merged