KS-14-4
smokewolfy/KotlinSprint pull request #67
Opened 2024-03-08 20:24 UTC by smokewolfy

2024-03-09 05:24 UTC, ievetrovdev requested changes

2024-03-09 05:24 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task4.kt
> +        satelliteList: MutableList<Satellite>
В некоторых классах у тебя есть trailling comma, в некоторых отсутствует. Лучше ставить. Но еще лучше соблюдать единый стиль везде.

2024-03-09 05:24 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task4.kt
> +    val satelliteList = planet.getSatelliteList().map { it.getName() }
Логичнее было бы вынести это в класс

2024-03-09 05:24 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task4.kt
> +) :
Тут лишний отступ

2024-03-09 14:59 UTC, smokewolfy commented on src/main/kotlin/lesson14/lesson14_task4.kt
> +        satelliteList: MutableList<Satellite>
Это для меня в новинку, стараюсь привыкнуть.

2024-03-10 08:13 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task4.kt
> +        satelliteList: MutableList<Satellite>
Это делает для удобства работы с гитом, при добавлении новой строки будет отображаться только она. Если же не использовать trailling comma, то будут видны 2 строки

2024-03-10 08:13 UTC, ievetrovdev approved these changes

2024-03-10 11:47 UTC, merged