KS-16-5
smokewolfy/KotlinSprint pull request #79
Opened 2024-03-24 17:17 UTC by smokewolfy

2024-03-25 07:10 UTC, ievetrovdev requested changes

2024-03-25 07:10 UTC, ievetrovdev commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +        if (health < 91) health += 10 else health = 100
> Смерть обнуляет силу удара, здоровье и **не позволяет лечиться**.

2024-03-25 07:12 UTC, smokewolfy commented on src/main/kotlin/lesson16/lesson16_task5.kt
> +        if (health < 91) health += 10 else health = 100
Понял. Принял.

2024-03-26 06:43 UTC, ievetrovdev approved these changes
Да, отлично

2024-03-26 14:32 UTC, merged